

INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY) 	values(1,'anu','SE','software','hyderabad',100,10,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY) 	values(2,'bhanu','SSE','networking','bangalore',200,20,200000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(3,'cnu','ASE','admin','hyderabad',300,30,500000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(4,'dhana','SE','software','chennai',100,10,150000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(5,'elie','TL','security','bangalore',400,40,1000000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(6,'firdoz','HR','recruitment','hyderabad',100,10,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(7,'sri','SE','software','chennai',200,20,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(8,'bindu','DTL','hardware','hyderabad',100,10,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(9,'sandhya','SE','software','hyderabad',300,30,450000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(10,'hari','SEA','software','hyderabad',100,10,120000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(11,'pawan','SE','software','bangalore',100,10,180000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(12,'prakash','SA','software','hyderabad',300,30,470000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(13,'srikanth','SE','software','hyderabad',100,10,140000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(14,'swathi','SE','software','chennai',100,10,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(15,'laxmi','SSE','software','hyderabad',200,20,220000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(16,'jyothi','ASE','software','bangalore',300,10,400000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(17,'sravi','SE','software','bangalore',100,10,160000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(18,'mokshu','SE','software','hyderabad',200,20,250000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(19,'purvik','SSE','software','hyderabad',100,10,100000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(20,'vamshi','SE','software','hyderabad',400,40,600000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(21,'mohan','MNG','software','bangalore',100,10,110000);
INSERT INTO employee(EMPLOYEE_ID,EMPLOYEE_NAME,TITLE,BUSINESS_UNIT,PLACE,SUPERVISOR_ID,COMPETENCY,SALARY)	values(22,'shiva','SA','software','hyderabad',400,40,650000);

