	CREATE TABLE EMPLOYEE (
	   EMPLOYEE_ID INT NOT NULL,
	   EMPLOYEE_NAME VARCHAR(50) NOT NULL,
	   TITLE VARCHAR(30) NOT NULL,
	   BUSINESS_UNIT VARCHAR(20)NOT NULL,
	   PLACE VARCHAR(30) NOT NULL,
	   SUPERVISOR_ID INT NOT NULL,
	   COMPETENCY INT NOT NULL,
	   SALARY INT NOT NULL,
	   PRIMARY KEY (EMPLOYEE_ID)
	);